[build]
  # Ye wo folder hai jise Netlify ko internet par dikhana hai
  # Agar aap React use kar rahe hain to "build", Vite ke liye "dist"
  publish = "dist" 

  # Ye command project ko build karne ke liye hai
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
